### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Majed0X** [revenge-mod/revenge-tweak#5]
Can we get [open in discord extension](https://github.com/BillyCurtis/OpenDiscordSafariExtension
) into prebuilt ipa please 

And other suggestion is to build revenge ipa’s with action function like bhtwitter like [bhtwitter](https://github.com/BandarHL/BHTwitter)

**Comment by Cristiandis** [comment]
Hello, i have my own custom builds that also include open in discord extension

**Comment by Cristiandis** [comment]
https://raw.githubusercontent.com/Cristiandis/RevengeTweak/Custom-Builds/notrack-repo.json

**Comment by Cristiandis** [comment]
> And other suggestion is to build revenge ipa’s with action function like bhtwitter like [bhtwitter](https://github.com/BandarHL/BHTwitter)

And we already do this

**Comment by Majed0X** [comment]
Yea for action stuff i dont seem to find it when i for the repo so thats why i was asking can u show me where it is sorry for the bother 

and for the open in discord I figured it will easier to prebuilt it in the action method if it’s possible

**Comment by Cristiandis** [comment]
> Yea for action stuff i dont seem to find it when i for the repo so thats why i was asking can u show me where it is sorry for the bother

just fork the repo, go to actions, enable them, go to build, click new workflow and paste a link the decrypted discord ipa

**Comment by Cristiandis** [comment]
for the open in discord same thing but you fork my own repo and build in the Custom-Builds branch, i cant upstream it because the way i did it is super jank but it works

**Comment by Majed0X** [comment]
Fork this [repo?](https://github.com/Cristiandis/RevengeTweak)?

**Comment by Cristiandis** [comment]
> Fork this [repo?](https://github.com/Cristiandis/RevengeTweak)?

yep

**Comment by Majed0X** [comment]
Alright thx
